databases:
  - name: ricardo_dev
    databaseName: ricardo_dev
    user: ricardo_dev_user

services:
  - type: web
    name: Transactrends
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ricardo_dev
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false