databases:
  - name: ricardo-postgresql
    databaseName: ricardo_postgresql
    user: ricardo_postgresql_user

services:
  - type: web
    name: TransactTrends
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ricardo-postgresql
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false